Script started on 2022-03-27 21:30:23+05:30 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="84" LINES="16"]
]0;jude@jude-Asus: ~/Mtech/Sem_2/NS/Assigments/3/NS_Lab3/server[01;32mjude@jude-Asus[00m:[01;34m~/Mtech/Sem_2/NS/Assigments/3/NS_Lab3/server[00m$ exit[Kexitpython3 server.py -n server -m S -q 10000
**************************Acting as a Server**************************
Listening ...
Connected with: ('127.0.0.1', 47832)
Connected to ('127.0.0.1', 47832)
Received From ('127.0.0.1', 47832): 601 request.
Signature matched for ('127.0.0.1', 47832)
Certificate of ('127.0.0.1', 47832) is valid.
Generated serverrandom key for connection with ('127.0.0.1', 47832)
Sent certificate to ('127.0.0.1', 47832)
Received From ('127.0.0.1', 47832): 603 request.
Decrypted the PreMasterKey from ('127.0.0.1', 47832)
Waiting for file request from ('127.0.0.1', 47832) ...
Received 605 request from ('127.0.0.1', 47832) for k
File k requested by ('127.0.0.1', 47832) not found.
Waiting for file request from ('127.0.0.1', 47832) ...
Received empty msg from ('127.0.0.1', 47832). Closing connection ...
^CTraceback (most recent call last):
  File "server.py", line 293, in <module>
    start()
  File "server.py", line 58, in start
    Server(myname,serverport)
  File "server.py", line 129, in Server
    conn, addr = skt.accept()
  File "/usr/lib/python3.8/socket.py", line 292, in accept
    fd, addr = self._accept()
KeyboardInterrupt

]0;jude@jude-Asus: ~/Mtech/Sem_2/NS/Assigments/3/NS_Lab3/server[01;32mjude@jude-Asus[00m:[01;34m~/Mtech/Sem_2/NS/Assigments/3/NS_Lab3/server[00m$ exit
exit

Script done on 2022-03-27 21:31:16+05:30 [COMMAND_EXIT_CODE="130"]
